# Site settings
title: Navi+ Help Center
site_name: "Help" # Display name next to logo in navbar
email: support@naviplus.io
description: "Navi+ Official Help Center - Find guides, tutorials, and support for optimizing your website's navigation, speed, and user experience with Navi+."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://help.naviplus.io" # The base hostname & protocol for your help site
social_image: "/assets/images/naviplus-social-share.jpg" # Default image for social sharing
twitter_username: "@NaviPlusOfficial" # Uncomment and replace with your Twitter handle if applicable
copyright_text: "Â© 2025 by Navi+"
copyright_url: "https://naviplus.io"
gitbook_source_link: https://help.shopifas.com/manual/website/help.naviplus.io.md
encoding: UTF-8

# Build settings
markdown: kramdown

# Jekyll Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/
    index: true
